### PR TITLE
Alguma otimização

### PR DESCRIPTION
**Pull request by cieko**

### CODE REVIEW

**Comment by cieko** [comment]
Eu estou aprendendo JavaScript. 😁

**Comment by camilazucchi** [comment]
योगदान के लिए बहुत धन्यवाद!

**Comment by cieko** [comment]
> योगदान के लिए बहुत धन्यवाद!

How did you know I can't speak Portuguese? I asked chatgpt for the translation ... 😂

**Comment by camilazucchi** [comment]
Since you kindly sent me the comment in Portuguese, I figured I should thank you in your language too (ChatGPT also helped me hehe).

**Comment by cieko** [comment]
Haha, okay okay

**Pull request merged**
